[template]
prefix = "haproxy-discover"
keys = [
  "services"
]

owner = "haproxy"
mode = "0644"
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"

check_cmd = "/usr/sbin/haproxy -c -f {{ .src }}"
reload_cmd = "nl-qdisc-add --dev=lo --parent=1:4 --id=40: --update plug --buffer &> /dev/null && /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid) && nl-qdisc-add --dev=lo --parent=1:4 --id=40: --update plug--release-indefinite &> /dev/null"
reload_cmd = "/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
